name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.digitalocean.com/tanmay/portfolio:latest
    
    - name: Login to DigitalOcean Container Registry
      run: docker login -u ${{ secrets.DO_TOKEN }} -p ${{ secrets.DO_TOKEN }} registry.digitalocean.com
    
    - name: Push Docker image to registry
      run: docker push registry.digitalocean.com/tanmay/portfolio:latest
